- create:
  - ~/.config

- link:
    ~/.config/alacritty: alacritty

- sudo:
  - aptget:
      alacritty:
          ppa_source: ppa:aslatter/ppa 
          upgrade: true
  - aptget: [fonts-hack-ttf, wmctrl, xdotool]

- shell:
  - 
    command: alacritty/install_hack_nerd_font.sh
    stdin: true
    stdout: true
    description: Install Hack Nerd Font
