- link:
    ~/.config/alacritty: alacritty

- ifarch:
  # - sudo:
  - paru:
    - alacritty
    - nerd-fonts-sf-mono 

- ifubuntu:
  - sudo:
    - aptget:
        alacritty:
            ppa_source: ppa:aslatter/ppa 
            upgrade: true
    - aptget: [fonts-hack-ttf]
  - shell:
    - 
      command: alacritty/install_hack_nerd_font.sh
      stdin: true
      stdout: true
      description: Install Hack Nerd Font
