- create:
  - ~/bin

- sudo:
  - aptget: [bc, bison, build-essential, ccache, curl, flex, g++-multilib, gcc-multilib, git, gnupg, gperf, imagemagick, lib32ncurses-dev, lib32readline-dev, lib32z1-dev, liblz4-tool, libncurses5, libncurses5-dev, libsdl1.2-dev, libssl-dev, libxml2, libxml2-utils, lzop, pngcrush, rsync, schedtool, squashfs-tools, xsltproc, zip, zlib1g-dev]

- shell:
  - ['curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo', Install repo...]
  - ['chmod a+x ~/bin/repo']
