- link:
    ~/.env/android_env: androiddev/android_env

- create:
  - ~/bin

- shell:
  - ['curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo', Install repo...]
  - ['wget -qO- https://dl.google.com/android/repository/platform-tools-latest-linux.zip | busybox unzip - -d ~/bin' , install adb and fastboot...]

- sudo:
  - aptget: [bc, bison, build-essential, ccache, curl, flex, g++-multilib, gcc-multilib, git, gnupg, gperf, imagemagick, lib32ncurses-dev, lib32readline-dev, lib32z1-dev, liblz4-tool, libncurses5, libncurses5-dev, libsdl1.2-dev, libssl-dev, libxml2, libxml2-utils, lzop, pngcrush, rsync, schedtool, squashfs-tools, xsltproc, zip, zlib1g-dev]
  - shell:
    - ['androiddev/install_adb_udev_config.sh ${USER}', install adb udev rules...]