- create:
  - $HOME/bin

- shell:
  - ['curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo', Install repo...]
  - ['chmod a+x ~/bin/repo']
  -
    command: meta/install_packages.sh android_build
    stdin: true
    stdout: true
    description: Installing packages
