
- link:
    ~/.profile: basic/profile
    ~/.bashrc: basic/bashrc
    ~/.bash_logout: basic/bash_logout



- shell:
  - [git submodule update --init --recursive, Installing submodules]
  -
    command: meta/install_packages.sh basic
    stdin: true
    stdout: true
    description: Installing packages
