- link:
    ~/.profile: bash/profile
    ~/.bashrc: bash/bashrc
    ~/.bash_logout: bash/bash_logout

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - ['basic/install-ripgrep-all.sh' , install riptrep-all]

- sudo:
  - aptget: [mc, cmake, p7zip-full, ripgrep, fzf, tree, pandoc, poppler-utils, ffmpeg]
