- link:
    ~/.profile: bash/profile
    ~/.bashrc: bash/bashrc
    ~/.bash_logout: bash/bash_logout

- shell:
  - [git submodule update --init --recursive, Installing submodules]

- sudo:
  - aptget: [mc, cmake, p7zip-full]
