- sudo :
  - aptget: [clangd-12, clang-format-12]
  - shell:
    - [update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-12 100, set clangd-12 as default]
    - [update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-12 100, set clang-format-12 as default]
