- sudo:
  - aptget: [libfprint-2-2, fprintd, libgusb-dev, libsystemd-dev, libpam-fprintd]
  - shell:
       - ["systemctl enable fprintd.service"]
       - ["systemctl start fprintd.service"] 
       - ["pam-auth-update --enable fprintd"]
