- link:
    ~/.vimrc: vim/vimrc
    ~/.config/nvim/init.vim: neovim/init.vim

- sudo :
  - aptget: 
     neovim:
        ppa_source: ppa:neovim-ppa/stable
        upgrade: true 
  - aptget: [nodejs, ruby-dev, python-is-python3, python3-pip, ack]
  - shell: [gem install neovim]
  - shell: [npm install -g neovim]
- shell:
  - [pip install pynvim && python3 -m pip install --upgrade pynvim]
  - [nvim +PlugInstall 4 +qall, Installing vim plugins]
