- link:
    ~/.config/nvim/init.lua: neovim/init.lua
    ~/.config/nvim/lua: neovim/lua
- sudo :
  - aptget: 
     neovim:
        ppa_source: ppa:neovim-ppa/unstable
        upgrade: true 
  - aptget: [python-is-python3, python3-pip, ack]
  # install needed packages to build matveyt/neoclip
  - aptget: [libluajit-5.1-dev, extra-cmake-modules, meson]
- shell:
  - [pip install pynvim && python3 -m pip install --upgrade pynvim]
  - [nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync']
#clipboard-sync is just a workadound needed for neoclip for wayland systems in 
#which wlr-data-control is not implemented
- cargo:
  - clipboard-sync
- shell: 
  - [wget -P "$HOME/.config/systemd/users/" https://raw.githubusercontent.com/dnut/clipboard-sync/master/clipboard-sync.service, download systemd service]
  - [systemctl --user enable --now clipboard-sync, enable systemd service]

