- link:
    ~/.vimrc: vim/vimrc
    ~/.config/nvim/init.vim: neovim/init.vim

- sudo :
  - aptget: [neovim, nodejs, ruby-dev, python-is-python3, python3-pip]
  - shell: [gem install neovim]
  - shell: [npm install -g neovim]
- shell:
  - [pip install pynvim && python3 -m pip install --upgrade pynvim]
  - [nvim +PlugInstall 4 +qall, Installing vim plugins]
