- sudo:
   - aptget:
      pipewire:
          ppa_source: ppa:pipewire-debian/pipewire-upstream 
          upgrade: true
   - aptget: [pipewire-audio-client-libraries, pipewire-pulse, pipewire-media-session, pipewire-bin, pipewire-locales, pipewire-tests, gstreamer1.0-pipewire, libpipewire-0.3-0, libpipewire-0.3-dev, libpipewire-0.3-modules, libspa-0.2-bluetooth, libspa-0.2-dev, libspa-0.2-jack, libspa-0.2-modules] 

- shell:
   - [systemctl --user daemon-reload]
   - [systemctl --user --now disable pulseaudio.service pulseaudio.socket]
   - [systemctl --user --now enable pipewire pipewire-pulse]
