- ifubuntu:
  - sudo:
    - shell:
        - ['wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > /usr/share/keyrings/signal-desktop-keyring.gpg']
        - ['echo "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main" | sudo tee /etc/apt/sources.list.d/signal-xenial.list']
    - aptget: [signal-desktop]
- ifarch:
  - paru:
    - signal-desktop
