- defaults:
   include:
    isolated: false

- include: 'meta/configs/common.yaml'

- link:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux/plugins/tpm: tmux/plugins/tpm

- ifubuntu:
  - sudo :
    - aptget: [tmux]

- ifarch:
  - paru:
    - tmux
- shell:
  - [~/.tmux/plugins/tpm/bin/install_plugins, Installing tmux plugins]
