- link:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux/plugins/tpm: tmux/plugins/tpm

- sudo :
  - aptget: [tmux, wl-clipboard]

- shell:
  - [~/.tmux/plugins/tpm/bin/install_plugins, Installing tmux plugins]
