- link:
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux/plugins/tpm: tmux/plugins/tpm

- shell:
  -
    command: meta/install_packages.sh tmux
    stdin: true
    stdout: true
    description: Installing packages

  - 
    command: ~/.tmux/plugins/tpm/bin/install_plugins
    stdin: true
    stdout: false
    description: Installing tmux plugins
