- include:
    path: 'meta/configs/common.yaml'
    isolated: False

- link:
    ~/.config/libinput-gestures.conf: touch/libinput-gestures.conf

- sudo:
  - aptget: [wmctrl, xdotool, libinput-tools]

- shell: ["rm -rf /tmp/libinput-gestures && git clone https://github.com/bulletmark/libinput-gestures.git /tmp/libinput-gestures"]
 
- sudo:
  - shell: ["cd /tmp/libinput-gestures && make install"]

- shell: ["rm -rf /tmp/libinput-gestures"]
