- link:
    ~/.vimrc: vim/vimrc

- sudo :
  - aptget: [vim-gtk, ruby-dev, python3-dev, xdg-utils, ruby-dev, clangd-12]
  - shell:
    - [update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-12 100, set clangd-12 as default]
- shell:
  - [vim +PlugInstall 4 +qall, Installing vim plugins]
