#deprecated - use neovim instead

- link:
    ~/.vimrc: vim/vimrc

- sudo :
  - aptget: [vim-gtk, python3-dev, xdg-utils, nodejs, ruby-dev, ack]
- shell:
  - [vim +PlugInstall 4 +qall, Installing vim plugins]
