#deprecated - use neovim instead

- link:
    ~/.vimrc: vim/vimrc
- ifubuntu:
  - sudo :
    - aptget: [vim-gtk, python3-dev, xdg-utils, nodejs, ruby-dev, ack]
- ifarch:
  - paru:
    - nodejs
    - ruby-dev
    - ack
    - python3-dev
    - vim-gtk

- shell:
  - [vim +PlugInstall 4 +qall, Installing vim plugins]
