- include:
    path: 'meta/configs/common.yaml'
    isolated: False

- link:
    ~/.config/dotfiles/nologin_env/xperia_env: xperia/xperia_env

- create:
  - ~/bin

- ifubuntu:
  - sudo:
     - aptget: [mono-complete]
- ifarch:
  - paru:
    - mono
- shell:
  - ['xperia/install_unsin.sh' , install unsin...]
  - ['xperia/install_newflasher.sh ', install newflasher]
  -
    command: xperia/install_xperifirm.sh
    stdin: true
    stdout: true
    description: install xperifirm
    quiet: false

