- include:
    path: 'meta/configs/common.yaml'
    isolated: False

- create:
  - ~/.config/dotfiles/completions

- link:
    ~/.zshrc: zsh/zshrc
    ~/.zshenv: zsh/zshenv

- ifubuntu:
  - sudo:
    - aptget: [zsh]

- ifarch:
  - paru:
    - zsh

- shell:
  - 
    command: zsh/make_zsh_default.sh
    stdin: true
    stdout: true
    description: Making zsh default

