- link:
    ~/.zshrc: zsh/zshrc
    ~/.zshenv: zsh/zshenv

- sudo:
  - aptget: [zsh]

- shell:
  - 
    command: zsh/make_zsh_default.sh
    stdin: true
    stdout: true
    description: Making zsh default

