
- link:
    ~/.zshrc: zsh/zshrc

- shell:
  -
    command: meta/install_packages.sh zsh
    stdin: true
    stdout: true
    description: Installing packages
  - 
    command: zsh/make_zsh_default.sh
    stdin: true
    stdout: true
    description: Making zsh default
