# Configure defaults
- defaults:
    include:
     isolated: True

# When only provided a string, that will be treated as the path of the file to include
- include: 'meta/configs/bash.yaml'
- include: 'meta/configs/zsh.yaml'
- include: 'meta/configs/tmux.yaml'
- include: 'meta/configs/neovim.yaml'
