- defaults:
    link:
        relink: true
        create: true
        force: true
    shell:
        stdout: true
        stderr: true
        quiet: true

- create:
  - $HOME/.config

- clean:
    ~/:
       force: true
    ~/.config:
       recursive: true
