set clipboard^=unnamed,unnamedplus
set relativenumber

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif


call plug#begin('~/.vim/plugged')
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

Plug 'junegunn/vim-plug'

" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plug 'rstacruz/sparkup', {'rtp': 'vim/'}
" Plug 'L9'
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
Plug 'ascenator/L9', {'name': 'newL9'}

"[1]themes
""" Theme / Pretty stuff
"""
Plug 'overcache/NeoSolarized'
Plug 'gruvbox-community/gruvbox'
Plug 'rakr/vim-togglebg'
" Awesome looking meta at bottom
" Fugitive will help with git related stuff, and show branch on statusline
Plug 'vim-airline/vim-airline' |
             \ Plug 'vim-airline/vim-airline-themes' |
             \ Plug 'bling/vim-bufferline' 
Plug 'tpope/vim-fugitive'
Plug 'jreybert/vimagit'
Plug 'duggiefresh/vim-easydir'
"[2] IDE

Plug 'ryanoasis/vim-devicons'
Plug 'airblade/vim-gitgutter'
Plug 'kshenoy/vim-signature'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'preservim/nerdcommenter'
Plug 'jackguo380/vim-lsp-cxx-highlight'

"[3]
"FocusGained and FocusLost autocommand events are not working in terminal vim.
"This plugin restores them when using vim inside Tmux.
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'christoomey/vim-tmux-navigator'
Plug 'christoomey/vim-tmux-runner'
Plug 'tmux-plugins/vim-tmux'

"[markdown]
"helps aligning MD tables  
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'habamax/vim-asciidoctor'
"[css]display colors in files
Plug 'ap/vim-css-color'

"[rust]

Plug 'rust-lang/rust.vim'
Plug 'dense-analysis/ale'
"[fuzzy file search]
"another plugin to jump to files slower but no dependencies 
Plug 'ctrlpvim/ctrlp.vim'
Plug 'dyng/ctrlsf.vim'
"TODO: check fzf
"Plug 'junegunn/fzf'


Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.0' }
Plug 'nvim-telescope/telescope-fzf-native.nvim', { 'do': 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' }
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
"[session management]
Plug 'tpope/vim-obsession'
Plug 'dhruvasagar/vim-prosession'
" Initialize plugin system
call plug#end()


set pastetoggle=<F2>

" Find files using Telescope command-line sugar.
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>
nmap     <C-F>f <Plug>CtrlSFPrompt 
nmap     <C-F>n <Plug>CtrlSFCwordPath
nmap     <C-F>p <Plug>CtrlSFPwordPath
let g:ctrlsf_compact_position = 'bottom_inside'
let g:ctrlsf_populate_qflist = 1
let g:ctrlsf_default_view_mode = 'compact'
"exclude .git and .gitignore from file search in ctrlp
let g:ctrlp_user_command = [
      \'.git', 
      \'cd %s && git ls-files -co --exclude-standard'] 
let g:ctrlp_show_hidden = 1      

let g:coc_global_extensions = [
      \ 'coc-json', 
      \ 'coc-git',
      \ 'coc-explorer',
      \ 'coc-clangd',
      \ 'coc-clang-format-style-options',
      \ 'coc-rust-analyzer']
let g:coc_user_config = {}
let g:coc_user_config['explorer.icon.enableNerdfont']='true'

nmap <space>e <Cmd>CocCommand explorer<CR>


if has('termguicolors')
set termguicolors
endif
syntax enable

set background=dark
let $GRUVBOX_DIR=expand("~/.vim/plugged/gruvbox")
if isdirectory($GRUVBOX_DIR)
    colorscheme gruvbox 
    " Hack to avoid first calling togglebg#map on <F5>
    let g:no_plugin_maps=1
    call togglebg#map("<F6>")
    unlet g:no_plugin_maps
endif

let g:airline#extensions#tabline#enabled = 1


" vim-gitgutter used to do this by default:
highlight! link SignColumn LineNr
let g:gitgutter_override_sign_column_highlight = 0
set colorcolumn=80

nnoremap <Leader>H :call<SID>LongLineHLToggle()<cr>
hi OverLength ctermbg=none cterm=none
match OverLength /\%>80v/
fun! s:LongLineHLToggle()
 if !exists('w:longlinehl')
  let w:longlinehl = matchadd('ErrorMsg', '.\%>80v', 0)
  echo "Long lines highlighted"
 else
  call matchdelete(w:longlinehl)
  unl w:longlinehl
  echo "Long lines unhighlighted"
 endif
endfunction

"asciidoc
" Fold sections, default `0`.
let g:asciidoctor_folding = 1

" Fold options, default `0`.
let g:asciidoctor_fold_options = 1
" Conceal *bold*, _italic_, `code` and urls in lists and paragraphs, default `0`.
" See limitations in end of the README
let g:asciidoctor_syntax_conceal = 1

" Highlight indented text, default `1`.
let g:asciidoctor_syntax_indented = 0

" List of filetypes to highlight, default `[]`
let g:asciidoctor_fenced_languages = ['python', 'c', 'javascript']


" rust
let g:rustfmt_autosave = 1
let g:rustfmt_emit_files = 1
let g:rustfmt_fail_silently = 0

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

if !has('nvim')
 set nocompatible              " be iMproved, required
 filetype off                  " required
 set encoding=UTF-8

 "add mouse support
 set mouse=a

 if has("mouse_sgr")
  set ttymouse=sgr
 else
  set ttymouse=xterm2
 end
 " vim private config
 set smarttab
 set hlsearch

endif

set cindent
set tabstop=2
set shiftwidth=2
" always uses spaces instead of tab characters
set expandtab
set number
set path+=**
set wildmenu

"FILE BROWSING:

filetype plugin on
" Tweaks for browsing
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

"disable arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

noremap <Leader>y "*y
noremap <Leader>p "*p
noremap <Leader>Y "+y
noremap <Leader>P "+p
autocmd BufRead,BufNewFile *.tmuxtheme set filetype=tmux
