name: Create Release Pull Requests
on:
  push:
    branches:
      - 'release*'

jobs:
  create-main-pr:
    name: Create Release PR Against main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Branch Info
        id: branch-info
        run: echo "::set-output name=name::${REF_TRIGGER##*/}"
        env:
          REF_TRIGGER: ${{ github.ref }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"                      # If blank, default: master
          pr_title: "Pulling ${{ steps.branch-info.outputs.name }} into main +semver: minor" # Title of pull request
          pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
          pr_reviewer: "walawrenci"                         # Comma-separated list (no spaces)
          pr_label: "release"                               # Comma-separated list (no spaces)
          github_token: ${{ secrets.GITHUB_TOKEN }}

  create-develop-pr:
    name: Create Release PR Against develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Branch Info
        id: branch-info
        run: echo "::set-output name=name::${REF_TRIGGER##*/}"
        env:
          REF_TRIGGER: ${{ github.ref }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"                      # If blank, default: master
          pr_title: "Pulling ${{ steps.branch-info.outputs.name }} into develop" # Title of pull request
          pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
          pr_reviewer: "walawrenci"                         # Comma-separated list (no spaces)
          pr_label: "release"                               # Comma-separated list (no spaces)
          github_token: ${{ secrets.GITHUB_TOKEN }}
